// Utility program to allow comparing the appearance of views generated by
// GroupedTableViewStyle with simple titles for headers and footers.
// 
// To display the UITableView with titles as headers and footers, set the value
// USE_TITLES_NOT_VIEWS to 1 and then compile and run the program.
// 
// To display the UITableView with views generated by GroupedTableViewStyle as
// headers and footers, set the value USE_TITLES_NOT_VIEWS to 0 and then compile
// and run the program.

#define USE_TITLES_NOT_VIEWS 0

#import <UIKit/UIKit.h>

@interface GroupedTableViewStyleViewController : UIViewController<UITableViewDataSource, UITableViewDelegate> {
  UITableView *tableView;
}

@property (nonatomic, retain) IBOutlet UITableView *tableView;

@end
